version: '3.8'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map nginx port to localhost
    depends_on:
      - backend
    volumes:
      - ./client:/app
    command: yarn run dev

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map backend port
    environment:
      - PORT=5000
      - REDIS_HOST=redis
      - MONGO_URI=mongodb+srv://mohamedisaac001:x5ZgiuRuaab1t3vF@cluster0.cmudw.mongodb.net/ai-productivity?retryWrites=true&w=majority&appName=Cluster0 # Replace with your MongoDB Atlas URI
    depends_on:
      - redis
    volumes:
      - ./server:/app
    command: npm run dev

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379" # Redis port
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis-data:
